### PR TITLE
Create masks_10.hcmask

### PR DESCRIPTION
**Pull request by i128**
Used for cracking randomly generated passwords of 10 characters in length

### CODE REVIEW

**Comment by roycewilliams** [comment]
What does this do that ?a?a?a?a?a?a?a?a?a?a doesn't?

**Comment by i128** [comment]
?a x 10 is a keyspace of 95^10
This hcmask file has a keyspace of (10^1 * 26^3 * 26^3 * 32^3) * 16800

A difference being, the above mask file is 97% smaller in keyspace to cover a more statistically likely range for randomly generated passwords. These files are in relation to an upcoming blog post where I go more in depth on explaining this.

**Comment by roycewilliams** [comment]
Yes, I'm familiar with the keyspaces.

By definition, "more statistically likely" and "randomly generated" are mutually exclusive. You can have one or the other, but not both.

**Comment by i128** [comment]
So thats the interesting part. Of a keyspace consisting of all 95 characters (although i noticed in practice a lot of random password generators do not include the space character) not all character classes are represented equally. For example, digits make up 10 out of the 95 possible choices (10.5%) a RNG selector can chose from.

With that in mind, given a large sample size certain character classes are more likely to appear. I.e you're more likely to encounter a password with all symbols than you are with one thats all digits when randomly generated.

You can take this a step further if there are password complexity requirements are enforced. Why test for all lower case possibilities in situations where we know that upper/lower/symbol/digit are required. etc.

**Comment by roycewilliams** [comment]
That's not the way randomness works.

Your digits vs specials analogy is the equivalent of having a table that is 2/3 blue and 1/3 red, and randomly dropping pennies on the table. Starting to pick up the pennies from the blue side of the table does not result in recovering _more pennies per time_.

**Comment by i128** [comment]
I think that's an important distinction, _more pennies per time spent_. 

The problem these masks are attempting to solve is for situations where people do not have the resources, be it time or hardware to do a full brute on longer passwords. If we know that certain character classes are more likely to appear than others AND we know specific class makeups (like no ?lx10) are used, then we can prioritize our cracking efforts by targeting those that are more common than others.

I do, however, agree that at some point, it does make sense to go with the full brute mode if users have that option.

**Pull request merged**
