### PR TITLE
Added pipal option to the menu

### PR DESCRIPTION
**Pull request by discoking**
Added new pipal option to the menu.

### CODE REVIEW

**Comment by Spoonman1091** [comment]
Sorry it took so long to get to this. I see a couple of issues though. 

My first test was for hash type 1000, which we split out LM and NT hashes and crack separately (hashfile.nt.out, hashfile.lm.out). Then, at the end, we put them back together into hashfile.out. In this case, you are running pipal against hashfile.nt.out, which only contains 1 instance per hash/password. It would need to run against hashfile.out to properly count multiple instances of the same hash/password.

Second, if the password contains certain characters, such as ":", it will be output from hashcat in HEX. So you have to convert this back to plaintext first. An example of this is in the export_excel() function, using binascii.unhexlify().

**Comment by discoking** [comment]
@Spoonman1091 thanks for the feedback, I thought I was being clever and avoiding an IF state on type 1000 by referencing the cleartext password in the [-1] position of the list since the output of 1000 has fewer elements than 5600. I will fix these two issues and resubmit the pull request.

**Comment by discoking** [comment]
I will also fix the cleanup of the temp files, I see there is a separate cleanup function.

**Comment by discoking** [comment]
@Spoonman1091 I added the two fixes, it now combines .nt.out and lm.out into one file before processing when the hashtype = 1000, and it unhexes the clear text passwords before they are added to the file that pipal processes. I also caught a bug where I wasn't closing the file that Pipal uses which lead to Pipal processing a blank file.

**Comment by discoking** [comment]
@Spoonman1091 this should be ready to test.

**Comment by Spoonman1091** [comment]
I love it! Thanks for the pull!

**Pull request merged**
